# Generated by Django 4.2.8 on 2024-01-17 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Изображение')),
                ('content', models.TextField(blank=True, verbose_name='Описание открытки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('time_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcard', to='postcard.category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='postcard_ca_name_d7c7f0_idx'),
        ),
        migrations.AddIndex(
            model_name='postcard',
            index=models.Index(fields=['id', 'slug'], name='postcard_po_id_02647d_idx'),
        ),
        migrations.AddIndex(
            model_name='postcard',
            index=models.Index(fields=['title'], name='postcard_po_title_71f3de_idx'),
        ),
        migrations.AddIndex(
            model_name='postcard',
            index=models.Index(fields=['-time_created'], name='postcard_po_time_cr_fb45ed_idx'),
        ),
    ]
