# Generated by Django 4.2.8 on 2024-01-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcard',
            options={'ordering': ['title'], 'verbose_name': 'Открытка', 'verbose_name_plural': 'Открытки'},
        ),
    ]
